application: waypastcurfewsite

version: 1
runtime: python27
api_version: 1
threadsafe: false

default_expiration: '365d'

skip_files: |
    ^(.*/)?(
    (app\.yaml)|
    (index\.yaml)| 
    (index\.yaml)|
    (\..*)|
    (.*\.pyc)|
    (.*\.bat)|
    (.*\.psd)|
    (Thumbs.db)|
    (.*\.svn/.*)|
    (.*\.lnk)|
    (.*\.datastore)|
    (_darcs/.*)|
    (nbproject/.*)|
    (.*\.swp)|
    (.*\.log)|
    )$

builtins:
- appstats: on
- deferred: on

handlers:
- url: /
  static_files: gui/index.html
  upload: index.html

- url: /
  static_dir: gui
